// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LightSaver.Migrations
{
    [DbContext(typeof(RokuSessionDbContext))]
    [Migration("20251202025414_InitialRokuSessionDbContext")]
    partial class InitialRokuSessionDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RokuSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Expired")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxScreenSize")
                        .HasColumnType("integer");

                    b.Property<bool>("ReadyForTransfer")
                        .HasColumnType("boolean");

                    b.Property<string>("RokuId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionCode")
                        .IsUnique();

                    b.ToTable("RokuSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
