// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LightSaver.Migrations.LightroomUpdateSessionDb
{
    [DbContext(typeof(LightroomUpdateSessionDbContext))]
    partial class LightroomUpdateSessionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LightroomUpdateSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("Links")
                        .IsRequired()
                        .HasColumnType("hstore");

                    b.Property<bool>("ReadyForTransfer")
                        .HasColumnType("boolean");

                    b.Property<string>("RokuId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UpdateSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
