name: Initial Deployment to Azure Step 1

on:
  workflow_dispatch:

jobs:
  build-test:
    uses: wrossman/LightSaver-Web-App/.github/workflows/build-test.yaml

  iac-deploy:
    uses: wrossman/LightSaver-Web-App/.github/workflows/iac-deploy.yaml
    secrets: inherit
    with:
      deployment_name: ${{ vars.DEPLOYMENT_NAME }}