name: Initial Deployment to Azure Step 1

on:
  workflow_dispatch:

jobs:
  build-test:
    uses: ./.github/workflows/modules/build-test.yaml

  iac-deploy:
    uses: ./.github/workflows/modules/iac-deploy.yaml
    secrets: inherit
    with:
      deployment_name: ${{ vars.DEPLOYMENT_NAME }}