name: Initial Deployment to Azure Step 2

on:
  workflow_dispatch:

jobs:
  create-db-webapp-user:
    uses: ./.github/workflows/create-db-webapp-user.yaml
    secrets: inherit
    with:
      deployment_name: ${{ vars.DEPLOYMENT_NAME }}

  deploy-app-service:
    uses: ./.github/workflows/deploy-app-service.yaml
    secrets: inherit
    with:
      deployment_name: ${{ vars.DEPLOYMENT_NAME }}