name: Initial Deployment to Azure Step 2

on:
  workflow_dispatch:

jobs:
  create-db-webapp-user:
    uses: wrossman/LightSaver-Web-App/.github/workflows/create-db-webapp-user.yaml@main
    secrets: inherit
    with:
      deployment_name: ${{ vars.DEPLOYMENT_NAME }}

  deploy-app-service:
    uses: wrossman/LightSaver-Web-App/.github/workflows/deploy-app-service.yaml@main
    secrets: inherit
    with:
      deployment_name: ${{ vars.DEPLOYMENT_NAME }}