name: Module - Build and Test

on:
  workflow_call:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v6

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test