# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Module - Deploy IAC

on:
  workflow_call:
    inputs:
      deployment_name:
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v6

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Bicep Deploy
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: create
          name: Development
          scope: resourceGroup
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
          resource-group-name: lightsaver-rg
          template-file: ./iac/main.bicep
          parameters: '{"deploymentName": "${{ inputs.deployment_name }}",
            "sqlServerPassword": "${{ secrets.SQL_SERVER_PASSWORD}}",
            "googleOAuthClientId": "${{ secrets.GOOGLE_CLIENT_ID}}",
            "googleOAuthClientSecret": "${{ secrets.GOOGLE_CLIENT_SECRET}}",
            "hmacServerKey": "${{ secrets.HMAC_SERVER_KEY}}"}'

      - name: Force User Managed Identity for WebApp KeyVault access
        uses: Azure/cli@v2.2.0
        env:
          RESOURCE_GROUP: lightsaver-rg
          DEPLOYMENT_NAME: ${{ inputs.deployment_name }}
          IDENTITY_NAME: lightsaver-webapp-identity
        with:
          azcliversion: latest
          inlineScript: |
            set -euo pipefail

            WEBAPP_NAME="${DEPLOYMENT_NAME}-webapp"

            identityResourceId="$(az identity show \
              --resource-group "$RESOURCE_GROUP" \
              --name "$IDENTITY_NAME" \
              --query id -o tsv)"

            az webapp update \
              --resource-group "$RESOURCE_GROUP" \
              --name "$WEBAPP_NAME" \
              --set keyVaultReferenceIdentity="$identityResourceId"