name: Module - Create DB WebApp User and Migrate Database

on:
  workflow_call:
    inputs:
      deployment_name:
        required: true
        type: string

jobs:
  create-db-webapp-user-migrate:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v6

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Create Web App database user from managed identity
        uses: azure/sql-action@v2.3
        with:
          connection-string: 'Server=tcp:${{ inputs.deployment_name }}-sqlserver.database.windows.net,1433;Initial Catalog=lightsaver-db;Authentication=Active Directory Default;'
          path: './iac/sql/create-webapp-user.sql'

      - name: Restore
        run: dotnet restore ./src/api/LightSaver.csproj

      - name: Build project
        run: dotnet build ./src/api/LightSaver.csproj --no-restore

      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef

      - name: Apply Initial Database Migration
        run: dotnet ef database update --no-build --verbose --project ./src/api/LightSaver.csproj --connection "Server=tcp:${{ inputs.deployment_name }}-sqlserver.database.windows.net,1433;Initial Catalog=lightsaver-db;Authentication=Active Directory Default;"