name: Orchestration - Initial Deployment to Azure Step 1

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-test:
    uses: ./.github/workflows/module-build-test.yaml

  iac-deploy:
    needs: build-test
    uses: ./.github/workflows/module-iac-deploy.yaml
    secrets: inherit
    with:
      deployment_name: ${{ vars.DEPLOYMENT_NAME }}