name: Orchestration - Initial Deployment to Azure Step 2

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  create-db-webapp-user:
    uses: ./.github/workflows/module-create-db-webapp-user.yaml
    secrets: inherit
    with:
      deployment_name: ${{ vars.DEPLOYMENT_NAME }}

  deploy-app-service:
    needs: create-db-webapp-user
    uses: ./.github/workflows/module-deploy-app-service.yaml
    secrets: inherit
    with:
      deployment_name: ${{ vars.DEPLOYMENT_NAME }}